### ISSUE TITLE
手机端后台插件设置页面为空

### ISSUE THREAD

**Issue by SuperTylerX** [iamxjb/rest-api-to-miniprogram#10]
https://github.com/iamxjb/rest-api-to-miniprogram/blob/12714ea5c20c18b0d74b558e2d9fdf6f92b937a6/includes/settings/wp-wechat-config.php#L133

排查了一番，原因是133行多出了这一层div（还没有结尾的反括号）导致手机端不显示。

去掉这一行即可正常显示了。

![img](https://tva1.sinaimg.cn/large/006RKGBpgy1gsld39o8fyj60bi0kkaaz02.jpg)

![img](https://tva1.sinaimg.cn/large/006RKGBpgy1gsld6px2t8j60b50khq4j02.jpg)

**Comment by iamxjb** [comment]
已修复
