### ISSUE TITLE
openId 存储需要大小写敏感

### ISSUE THREAD

**Issue by PascalSun** [iamxjb/rest-api-to-miniprogram#2]
openId 需要大小写敏感存储，不然后面给该用户发送模版消息会失败

**Comment by PascalSun** [comment]
两种解决方式

- 增加一个字段，利用目前的activation_key 字段来存储大小写敏感的openid
- 或者，因为邮箱是使用openid生成的，也是大小写敏感的，直接从邮箱里提取openId

**Comment by iamxjb** [comment]
谢谢，这问题我倒是没注意，因为我的服务器是windows的操作系统，所以没有发现这个问题。你的服务器是Linux吧？如果方便可以加我的微信交流下,我的微信号：iamxjb

**Comment by PascalSun** [comment]
我加了你微信了，Sun
另外我觉得，有issue直接可以在这里讨论，开源吧，前面踩的坑后面人能看到，你也省下回答一样问题的时间
