### ISSUE TITLE
我无法在5.2.3上使用

### ISSUE THREAD

**Issue by yulianjie** [iamxjb/rest-api-to-miniprogram#6]
我的系统环境是centos7，php7.2，用宝塔面板搭建的wordpress，版本是5.2.3，产生了下面的错误

> Fatal error: Cannot redeclare get_client_ip() (previously declared in /www/wwwroot/blog.jackyu.club/wp-content/themes/lolimeow/modules/fun-user.php:62) in /www/wwwroot/blog.jackyu.club/wp-content/plugins/rest-api-to-miniprogram-master/includes/ram-util.php on line 446

**Comment by rieval** [comment]
你的博客主题和插件使用了相同的函数名

建议你将主题的 `modules/fun-user.php` 62 行左右的 get_client_ip 改成其他的字符串，并且全局搜索修改它

**Comment by iamxjb** [comment]
楼上的解答是对的，或者您也可以改下插件里的这个函数名。
